name: Testing the action
on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .
        with: 
          url: ${{ secrets.WEBHOOK }}
          title: NEW
          message: Hii
          